INSERT INTO [MSWSch].[MSWCfgFurmanCuentaContableGastosOntario]
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6015 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6024 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6028 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6045 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6046 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6047 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6047 AND ClaNiv2 = 20 AND ClaNiv3 = 120
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6049 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6050 AND ClaNiv2 = 20 AND ClaNiv3 = 120
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6052 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6054 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6054 AND ClaNiv2 = 20 AND ClaNiv3 = 120
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6055 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6062 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6063 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6064 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6065 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6066 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6068 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6068 AND ClaNiv2 = 20 AND ClaNiv3 = 120
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6073 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6073 AND ClaNiv2 = 20 AND ClaNiv3 = 1
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6075 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6075 AND ClaNiv2 = 20 AND ClaNiv3 = 120
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6084 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6084 AND ClaNiv2 = 20 AND ClaNiv3 = 120
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6090 AND ClaNiv2 = 20 AND ClaNiv3 = 700
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6091 AND ClaNiv2 = 20 AND ClaNiv3 = 700
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6098 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6099 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6100 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6102 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6103 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6104 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6104 AND ClaNiv2 = 20 AND ClaNiv3 = 120
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6106 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6107 AND ClaNiv2 = 20 AND ClaNiv3 = 120
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6114 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6591 AND ClaNiv2 = 20 AND ClaNiv3 = 0
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6811 AND ClaNiv2 = 20 AND ClaNiv3 = 120
UNION
SELECT IdCuentaContable, NumCuenta, 0, NULL, GETDATE(), 'CARGA INICIAL', 1 FROM MSWSch.MswTraCuentaContable9 WITH(NOLOCK) WHERE ClaNiv1 = 6816 AND ClaNiv2 = 20 AND ClaNiv3 = 120